version: '3.7'

services:
  auth:
    build:
      context: auth
      cache_from:
        - 999618886922.dkr.ecr.eu-west-3.amazonaws.com/auth:latest
    restart: unless-stopped
    ports:
    - 4000:3000/tcp
    environment:
      MONGODB_URL: mongodb://superb:superb@mongodb:27017/superb
    depends_on:
    - mongodb
  booking:
    build:
      context: booking
      cache_from:
        - 999618886922.dkr.ecr.eu-west-3.amazonaws.com/booking:latest
    restart: unless-stopped
    ports:
    - 4100:3000/tcp
    - 4101:3000/tcp
    environment:
      MONGODB_URL: mongodb://superb:superb@mongodb:27017/superb
    depends_on:
    - mongodb
  graphql:
    build:
      context: graphql
      cache_from:
        - 999618886922.dkr.ecr.eu-west-3.amazonaws.com/graphql:latest
    restart: unless-stopped
    ports:
    - 4200:3000/tcp
    environment:
      BOOKING_SERVICE_URI: booking:3000
      AUTH_SERVICE_URI: http://auth:3000
    depends_on:
    - booking
    - auth
  client:
    build:
      context: client
      target: dev
      cache_from:
        - 999618886922.dkr.ecr.eu-west-3.amazonaws.com/client-dev:latest
    restart: unless-stopped
    ports:
    - 4300:80/tcp
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: superb
      MONGO_INITDB_ROOT_USERNAME: superb
      MONGO_INITDB_ROOT_PASSWORD: superb
    restart: always
    volumes:
    - mongodbdata:/data/db
    - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
    - 27017:27017/tcp

volumes:
  mongodbdata:
    name: mongodbdata